### ISSUE TITLE
Criação do protótipo no Figma

### ISSUE THREAD

**Issue by iPedroV** [iPedroV/ads031#1]
Criação feita pelo João Paulo.

**Comment by iPedroV** [comment]
![image](https://user-images.githubusercontent.com/70039868/133355353-a71870e6-fced-4e9c-b40e-259f426d669b.png)

Print da tela de Login feita pelo @cmteferreira32 e revisada por mim @iPedroV

**Comment by cmteferreira32** [comment]
Versão Final
Protótipo do Aplicativo

https://www.figma.com/proto/nYj22IumNll98ugYXlL8iG/Untitled?node-id=1%3A2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A3&show-proto-sidebar=1
