### ISSUE TITLE
Criação do protótipo no Figma - Aviões para Comprar/Alugar/Fretar

### ISSUE THREAD

**Issue by iPedroV** [iPedroV/ads031#10]
Tela de Aviões para "[Comprar](https://www.figma.com/proto/nYj22IumNll98ugYXlL8iG/Untitled?node-id=27%3A122&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A3&show-proto-sidebar=1)";
Tela de Aviões para "[Alugar](https://www.figma.com/proto/nYj22IumNll98ugYXlL8iG/Untitled?node-id=81%3A210&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A3&show-proto-sidebar=1)";
Tela de Aviões para "[Fretar](https://www.figma.com/proto/nYj22IumNll98ugYXlL8iG/Untitled?node-id=81%3A112&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A3&show-proto-sidebar=1)".

**Comment by iPedroV** [comment]
![image](https://user-images.githubusercontent.com/70039868/133893795-038bb546-40e5-4bc0-b685-d29f93fa3427.png)![image](https://user-images.githubusercontent.com/70039868/133893825-37addc58-ed81-441c-9e4e-1073a12b9bc1.png)![image](https://user-images.githubusercontent.com/70039868/133893851-313b4444-3294-465d-adf0-fae7bc1b5ebd.png)

**Comment by thiagoalves02** [comment]
Tela de Compra/Aluguel/Frete feita pelo @cmteferreira32 foi revisada e validada, todos os componentes estão funcionais. @thiagoalves02
