### ISSUE TITLE
Criação do protótipo no Figma - Enviar mensagem

### ISSUE THREAD

**Issue by iPedroV** [iPedroV/ads031#11]
Tela de "[Enviar mensagem](https://www.figma.com/proto/nYj22IumNll98ugYXlL8iG/Untitled?node-id=121%3A48&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A3&show-proto-sidebar=1)".

Mensagem após a tela de enviar mensagem "[Mensagem enviada!](https://www.figma.com/proto/nYj22IumNll98ugYXlL8iG/Untitled?node-id=121%3A91&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A3&show-proto-sidebar=1)".

**Comment by iPedroV** [comment]
![image](https://user-images.githubusercontent.com/70039868/133893920-c9df8f33-6fde-4af4-a3a4-7a96d9fe9b28.png)

**Comment by Gabriel1104-King** [comment]
Excelente meio de comunicação,as vezes da um atraso mas depois flui muito bem.
