### ISSUE TITLE
Criação do protótipo no Figma - Feed de Notícias

### ISSUE THREAD

**Issue by iPedroV** [iPedroV/ads031#12]
Tela do "[Feed de Notícias](https://www.figma.com/proto/nYj22IumNll98ugYXlL8iG/Untitled?node-id=16%3A29&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A3&show-proto-sidebar=1)".

**Comment by iPedroV** [comment]
![image](https://user-images.githubusercontent.com/70039868/133894109-c236baed-8ca7-4486-a537-fedcd8b3fe28.png)

**Comment by Erickdejesuslima** [comment]
gostei muito do design aplicado, simples, intuitivo, e de fácil compreensão da funcionalidade para o usuário

**Comment by Erickdejesuslima** [comment]
O titulo em vermelho como destaque e as cores utilizadas trazem um design limpo para a tela do feed de noticias
