### ISSUE TITLE
Criação do protótipo no Figma - Tela principal

### ISSUE THREAD

**Issue by iPedroV** [iPedroV/ads031#2]
Tela "[Principal](https://www.figma.com/proto/nYj22IumNll98ugYXlL8iG/Untitled?node-id=1%3A3&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A3&show-proto-sidebar=1)".

**Comment by iPedroV** [comment]
![image](https://user-images.githubusercontent.com/70039868/133892916-2af1f463-5157-43a3-a739-a1c461d49cba.png)

**Comment by thiagoalves02** [comment]
Tela de Principal feita pelo @cmteferreira32 foi revisada e validada, todos os componentes estão funcionais. @thiagoalves02
