### ISSUE TITLE
Criação do protótipo no Figma - Entrar com Facebook

### ISSUE THREAD

**Issue by iPedroV** [iPedroV/ads031#3]
Tela "[Login com Facebook](https://www.figma.com/proto/nYj22IumNll98ugYXlL8iG/Untitled?node-id=107%3A2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A3&show-proto-sidebar=1)".

**Comment by iPedroV** [comment]
![image](https://user-images.githubusercontent.com/70039868/133892954-d143bfb2-b073-4a4f-90a1-594093a1ea7b.png)

**Comment by Marcos436** [comment]
ótimo , ficou padrão o acesso pelo Facebook !!
