### ISSUE TITLE
Criação do protótipo no Figma - Esqueci a senha

### ISSUE THREAD

**Issue by iPedroV** [iPedroV/ads031#4]
Tela de "[Esqueci a senha](https://www.figma.com/proto/nYj22IumNll98ugYXlL8iG/Untitled?node-id=164%3A587&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A3&show-proto-sidebar=1)".

Mensagem após a tela de esqueci a senha "[E-mail de recuperação enviado com sucesso](https://www.figma.com/proto/nYj22IumNll98ugYXlL8iG/Untitled?node-id=279%3A21&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A3&show-proto-sidebar=1)".

**Comment by iPedroV** [comment]
![image](https://user-images.githubusercontent.com/70039868/133893051-11ef5e99-e69c-4b68-b2b3-61ac19e9f84f.png)

**Comment by Gabriel1104-King** [comment]
Geralmente quando esqueço minhas senhas,demoram minutos ou até horas para me ajudarem. O suporte aqui foi ótimo e em segundos resolvi.
