### ISSUE TITLE
Testes das telas para a entrega

### ISSUE THREAD

**Issue by iPedroV** [iPedroV/ads031#47]

**Comment by iPedroV** [comment]
Testes concluidos

**Comment by Marcos436** [comment]
acesso pela a tela de login realizada pelo cadastro (crie sua conta), campos 1 (Nome de Usuário:), 2(E-mail:) 3 (Senha:) 4 (Confirme sua senha:) informações adicionadas e o botão (cadastrar) acionado dando acesso a tela home realizado com sucesso ! 

![image](https://user-images.githubusercontent.com/70240903/145096366-10ccd354-2a9b-46a6-af27-7688e1af70b2.png)

acesso pelo campo de login(Digite seu e-mail:), senha (Digite sua senha:) realizado dando acesso a tela inicial(home) campos testados separadamente com seus alertas de  mensagens de erro por falta de senha aparecendo The password is invalid or the user does not have a password.(A senha é inválida ou o usuário não possui uma senha.) mensagem de erro por falta de informação no campo de login, The email address is badly formatted.(O endereço de e-mail está formatado incorretamente.) realizado com sucesso! 

![image](https://user-images.githubusercontent.com/70240903/145096511-3599c4fc-5488-48b5-bd93-f5d57b4122c7.png)


teste de recuperação de senha  feito com sucesso : 
![image](https://user-images.githubusercontent.com/70240903/145096099-e758d3e1-ba6e-4503-be9e-22b29e2c48e0.png)


teste de compra clicando no modelo acessando as informações sobre os modelos e definindo um data de pretensão de compra realizado com sucesso : 
 
![image](https://user-images.githubusercontent.com/70240903/145097843-e24857cc-445c-480a-a2fc-01a6872d6df3.png)


teste de a alugar e frete realizado com sucesso :

![image](https://user-images.githubusercontent.com/70240903/145103434-3df93d73-9934-4094-97b9-eb8f1607864e.png)

**Comment by Marcos436** [comment]
teste adicionando as escolhas a tela favoritos da compra do aluguel e fretes  realizado com sucesso !
