### ISSUE TITLE
Criação do protótipo no Figma - Entrar com Google

### ISSUE THREAD

**Issue by iPedroV** [iPedroV/ads031#5]
Tela de "[Entrar com Google](https://www.figma.com/proto/nYj22IumNll98ugYXlL8iG/Untitled?node-id=119%3A32&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A3&show-proto-sidebar=1)".

**Comment by iPedroV** [comment]
![image](https://user-images.githubusercontent.com/70039868/133893300-e81a82cb-e130-482d-968a-999233f0771e.png)

**Comment by danielc-957** [comment]
Tela de funcionalidade - "Entrar com Google" feita pelo @cmteferreira32 foi verificada e validada. O protótipo apresenta a ação esperada no acionamento do botão, levando ao setor de Login com a conta do Google. @danielc-957 .
