### ISSUE TITLE
Criação do protótipo no Figma - Cadastre-se

### ISSUE THREAD

**Issue by iPedroV** [iPedroV/ads031#6]
Tela de "[Cadastro](https://www.figma.com/proto/nYj22IumNll98ugYXlL8iG/Untitled?node-id=164%3A563&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A3&show-proto-sidebar=1)".

**Comment by iPedroV** [comment]
![image](https://user-images.githubusercontent.com/70039868/133893357-a853afaf-ecdd-4b9f-a579-2f8d00f20f61.png)

**Comment by Marcos436** [comment]
Pedro, observando aqui e testando... notei que quando entrar para fazer cadastro com uma rede social na palavra  de "voltar" localizado no canto superior direito , apertando na seta ele não volta tem que aperta bem encima da palavra "voltar", não seria melhor deixarmos apenas a palavra ou a seta já que a mesma já e auto intuitiva ?!! o que vocês acham ?
