### ISSUE TITLE
Criação do protótipo no Figma - Por que comprar uma aeronave

### ISSUE THREAD

**Issue by iPedroV** [iPedroV/ads031#8]
Tela "[Por que comprar uma aeronave](https://www.figma.com/proto/nYj22IumNll98ugYXlL8iG/Untitled?node-id=121%3A130&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A3&show-proto-sidebar=1)".

**Comment by iPedroV** [comment]
![image](https://user-images.githubusercontent.com/70039868/133893599-c683bfcf-eef6-4239-962d-8608d5dc1395.png)

**Comment by danielc-957** [comment]
Tela de informação - "Por que comprar uma aeronave ? " feita pelo @cmteferreira32  foi verificada e validada. As ações e informações apresentadas na tela em destaque seguem os padrões do restante do aplicativo. @danielc-957.
