### ISSUE TITLE
Criação do protótipo no Figma - Filtros para Comprar/Alugar/Fretar

### ISSUE THREAD

**Issue by iPedroV** [iPedroV/ads031#9]
Tela com os filtros para "[Comprar](https://www.figma.com/proto/nYj22IumNll98ugYXlL8iG/Untitled?node-id=13%3A13&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A3&show-proto-sidebar=1)";
Tela com os filtros para "[Alugar](https://www.figma.com/proto/nYj22IumNll98ugYXlL8iG/Untitled?node-id=13%3A16&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A3&show-proto-sidebar=1)";
Tela com os filtros para "[Fretar](https://www.figma.com/proto/nYj22IumNll98ugYXlL8iG/Untitled?node-id=13%3A6&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A3&show-proto-sidebar=1)".

**Comment by iPedroV** [comment]
![image](https://user-images.githubusercontent.com/70039868/133893747-c7a94b06-4912-42f7-a3eb-7a2969bfbaaa.png) ![image](https://user-images.githubusercontent.com/70039868/133893705-332018ff-ce81-40d1-be5a-016c0c15d23a.png) ![image](https://user-images.githubusercontent.com/70039868/133893712-f3891cb4-40d5-4d46-a109-b9dc9f9759da.png)

**Comment by Erickdejesuslima** [comment]
gostei muito do design aplicado, simples, intuitivo, e de fácil compreensão da funcionalidade para o usuário
